### ISSUE TITLE
腾讯云redis同步云资源报错

### ISSUE THREAD

**Issue by niubaoxing** [starsliao/TenSunS#99]
腾讯云redis同步云资源报错
![image](https://github.com/starsliao/TenSunS/assets/52197779/2e897f36-f6eb-4831-890a-29e235917378)

**Comment by niubaoxing** [comment]
![image](https://github.com/starsliao/TenSunS/assets/52197779/060b10bb-4f3f-490e-81fa-9de1e1cb6103)
10:26:02 | ERROR | name 'logger' is not defined
Traceback (most recent call last):
  File "/flask/units/cloud/tencent_cloud.py", line 264, in redis
    off,on = sync_redis.w2consul('tencent_cloud',account,region,redis_dict)
  File "/flask/units/cloud/sync_redis.py", line 74, in w2consul
    logger.info(f"{account}:code: 5000, data: {reg.status_code}:{reg.text}")
NameError: name 'logger' is not defined

10:26:05 | ERROR | name 'logger' is not defined
Traceback (most recent call last):
  File "/flask/units/cloud/tencent_cloud.py", line 264, in redis
    off,on = sync_redis.w2consul('tencent_cloud',account,region,redis_dict)
  File "/flask/units/cloud/sync_redis.py", line 74, in w2consul
    logger.info(f"{account}:code: 5000, data: {reg.status_code}:{reg.text}")
NameError: name 'logger' is not defined

172.21.0.3 - - [13/Nov/2023 10:26:05] "POST /api/jobs HTTP/1.0" 200 -

**Comment by niubaoxing** [comment]
hello 这个是程序逻辑问题吗

**Comment by niubaoxing** [comment]
又有了新bug。  一共5个redis 只显示了2个。而且按照分组 把其他的实例的监控。融合到一起了 
<img width="1202" alt="image" src="https://github.com/starsliao/TenSunS/assets/52197779/6db37b59-4d92-4947-bfbc-c825ef1530e7">

**Comment by niubaoxing** [comment]
<img width="1157" alt="image" src="https://github.com/starsliao/TenSunS/assets/52197779/6411aa6b-2d16-471b-9880-16244712ec63">
